"""Project constants and built-in vocabularies."""

SCHEMA_VERSION = "1.0"
PACKAGE_VERSION = "0.1.0a3"
DIGEST_ALGORITHM = "sha256"
CHAIN_ALGORITHM = "aiauditlog-sha256-chain-v1"
SIGNATURE_ALGORITHM = "ed25519"

RESERVED_NAMESPACES = {
    "agent",
    "audit",
    "benchmark",
    "component",
    "configuration",
    "data",
    "evaluation",
    "model",
    "policy",
    "replacement",
    "retrieval",
    "review",
    "security",
    "system",
    "tool",
}

CORE_EVENT_TYPES = {
    "system.started",
    "system.stopped",
    "configuration.loaded",
    "configuration.changed",
    "component.health_changed",
    "agent.created",
    "agent.started",
    "agent.delegated",
    "agent.step.started",
    "agent.step.completed",
    "agent.step.failed",
    "agent.escalated",
    "agent.completed",
    "agent.failed",
    "model.invocation.started",
    "model.invocation.completed",
    "model.invocation.failed",
    "model.response.rejected",
    "model.fallback.selected",
    "model.route.selected",
    "tool.call.requested",
    "tool.call.allowed",
    "tool.call.denied",
    "tool.call.started",
    "tool.call.completed",
    "tool.call.failed",
    "tool.result.redacted",
    "data.access.requested",
    "data.access.allowed",
    "data.access.denied",
    "data.read",
    "data.written",
    "data.deleted",
    "retrieval.started",
    "retrieval.completed",
    "retrieval.citation_used",
    "retrieval.citation_rejected",
    "policy.evaluation.started",
    "policy.evaluation.completed",
    "policy.decision.allowed",
    "policy.decision.denied",
    "policy.decision.review_required",
    "policy.decision.indeterminate",
    "policy.obligation.applied",
    "policy.bundle.changed",
    "review.requested",
    "review.assigned",
    "review.approved",
    "review.rejected",
    "review.expired",
    "review.cancelled",
    "security.prompt_injection.detected",
    "security.secret.detected",
    "security.pii.detected",
    "security.redaction.applied",
    "security.limit.exceeded",
    "security.integrity.failure",
    "security.authentication.failure",
    "security.authorization.failure",
    "evaluation.started",
    "evaluation.completed",
    "evaluation.failed",
    "benchmark.case.completed",
    "benchmark.constraint.failed",
    "replacement.decision.created",
    "audit.stream.created",
    "audit.stream.rotated",
    "audit.stream.closed",
    "audit.chain.verified",
    "audit.chain.failed",
    "audit.export.created",
    "audit.redaction.applied",
}

OUTCOME_STATUSES = {
    "success",
    "failure",
    "denied",
    "cancelled",
    "pending",
    "partial",
    "indeterminate",
    "skipped",
}

CLASSIFICATIONS = {"public", "internal", "confidential", "restricted"}

SECRET_KEYS = {
    "password",
    "passwd",
    "secret",
    "api_key",
    "token",
    "access_token",
    "refresh_token",
    "private_key",
    "authorization",
    "cookie",
    "credential",
}
